# Generated by Django 3.2.19 on 2023-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20230620_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
