# Generated by Django 3.2.19 on 2023-06-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_usermaster_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
