# Generated by Django 3.2.19 on 2023-06-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_usermaster_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='user_name',
            new_name='username',
        ),
    ]
