# Generated by Django 3.2.19 on 2023-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230703_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='activation_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
