# Generated by Django 3.2.19 on 2023-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_usermaster_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='act_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
