# Generated by Django 3.2.19 on 2023-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_prodmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
