# Generated by Django 3.2.19 on 2023-07-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_usermaster_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='act_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
