# Generated by Django 3.2.19 on 2023-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_active',
            field=models.CharField(max_length=50),
        ),
    ]
